- name: My first play
  hosts: nodes
  tasks:
   - name: Ping my hosts
     ansible.builtin.ping:

   - name: Print message
     ansible.builtin.debug:
      msg: Hello world

  - name: Install prerequisites packages at the latest version
    ansible.buitlin.yum:
      name: "{{item}}"
      state: "present"
    loop:
      - httpd
      - git
      - python3
      - python3-pip
      - nodejs
      - npm
      - mysql-server

  # - name: Start services after installation
  #   systemd_service:
  #     name: "{{item}}"
  #     enabled: yes
  #     state: started
  #   loop:
  #     - httpd
  #     - nodejs
  #     - npm
  #     - mysql-server