---
- name: deploy common configuration
  hosts: nodes
  remote_user: coke
  become: yes
  roles:
    - lamp-undo
  vars:
    action: "undo_web"

- name: deploy common configuration
  hosts: nodes
  remote_user: coke
  become: yes
  roles:
    - lamp-undo
  vars:
    action: "undo_db"