# - name: pre-requisites of the machine
#   hosts: nodes
#   remote_user: coke
#   become: yes
#   include_role:
#     name: installation
#   vars:
#     action: "install"

- name: Pass variables to role
  include_role:
    name: installation
  # vars:
  #   action: 'install'