---
- name: Install MariaDB package
  yum: 
    name: "{{ item }}" 
    state: installed
  loop:
   - mariadb-server
   - MySQL-python

- name: Configure SELinux to start mysql on any port
  seboolean: 
    name: mysql_connect_any 
    state: true 
    persistent: yes

- name: restart mariadb
  service: 
    name: mariadb 
    state: restarted

- name: Create MariaDB log file
  file: 
    path: /var/log/mysqld.log 
    state: touch 
    owner: mysql 
    group: mysql 
    mode: 0775

- name: Create MariaDB PID directory
  file: 
    path: /var/run/mysqld 
    state: directory 
    owner: mysql 
    group: mysql 
    mode: 0775

- name: Start MariaDB Service
  service: 
    name: mariadb 
    state: started 
    enabled: yes

- name: Create Application Database
  mysql_db: 
    name: "{{ dbname }}" 
    state: present

- name: Create Application DB User
  mysql_user: 
    name: "{{ dbuser }}" 
    password: "{{ upassword }}" 
    priv: '*.*:ALL'
    host: '%'
    state: present

- name: Copy database dump file
  template:
    src: "nodes_email.sql.j2"
    dest: /tmp
    mode: 0644

- name: Restore database
  mysql_db:
    name: "{{ dbname }}"
    state: import
    target: /tmp/nodes_email.sql.j2

