---
# tasks file for web-servers
- name: Install httpd and php
  yum: 
    name: "{{ item }}" 
    state: present
  loop:
   - httpd
   - php
   - php-mysql

- name: Install web role specific dependencies
  yum: 
    name: "{{ item }}" 
    state: installed
  loop:
   - git

- name: http service state
  service: 
    name: httpd 
    state: started 
    enabled: yes

- name: Configure SELinux to allow httpd to connect to remote database
  seboolean: 
    name: httpd_can_network_connect_db 
    state: true 
    persistent: yes

- name: Copy the code from repository
  git: 
    repo: "{{ automation_repository }}" 
    dest: /var/www/html/

# - name: Creates the index.php file
#   template: 
#     src: index.php.j2 
#     dest: /var/www/html/index.php





