---
# tasks file for web-servers
- name: definition of uninstallation vars
  set_fact:
    inst: "absent"
  when: action == "uninstall"

- name: definition of installation vars
  set_fact:
    inst: "present"
  when: action == "install"

- name: stop services before uninstallation
  systemd_service:
    name: "{{item}}"
    state: stopped
  loop:
    - httpd
    - nodejs
    - npm
    - mysql-server
  when: inst == "absent"


- name: Install/uninstall prerequisites packages at the latest version
  yum:
    name: "{{item}}"
    state: "{{inst}}"
  loop:
    - httpd
    - git
    - python3
    - python3-pip
    - nodejs
    - npm
    - mysql-server

- name: start services after installation
  systemd_service:
    name: "{{item}}"
    enabled: yes
    state: started
  loop:
    - httpd
    - nodejs
    - npm
    - mysql-server
  when: inst == "present"

