---
- name: Install prerequisites packages at the latest version
  yum:
    name: "{{item}}"
    state: "present"
  loop:
    - httpd
    - git
    - python3
    - python3-pip
    - nodejs
    - npm
    - mysql-server

- name: Start services after installation
  systemd_service:
    name: "{{item}}"
    enabled: yes
    state: started
  loop:
    - httpd
    - nodejs
    - npm
    - mysql-server