---
- name: Ensure PyMySQL is installed for Ansible MySQL modules
  pip:
    name: PyMySQL
    executable: pip3

- name: Start MariaDB Service (to allow DB modifications)
  service:
    name: mariadb
    state: started
    enabled: yes
  ignore_errors: yes

- name: Remove Application DB User
  community.mysql.mysql_user:
    name: lamp_user
    host: "%"
    state: absent
    login_user: root
    login_password: root
  ignore_errors: yes

- name: Remove Application Database
  community.mysql.mysql_db:
    name: lamp_db
    state: absent
    login_user: root
    login_password: root
  ignore_errors: yes

- name: Stop MariaDB Service
  service:
    name: mariadb
    state: stopped
  ignore_errors: yes

- name: Remove database dump file
  file:
    path: /tmp/dump.sql
    state: absent

- name: Delete MariaDB PID directory
  file:
    path: /var/run/mariadb
    state: absent

- name: Delete MariaDB log file
  file:
    path: /var/log/mariadb/mariadb.log
    state: absent

- name: Remove MariaDB package
  package:
    name: "{{ item }}"
    state: absent
  loop:
    - mariadb-server
    - MySQL-python
  ignore_errors: yes
